global:
  resolve_timeout: 5m

route:
  receiver: default-webhook
  group_by: ["alertname", "component"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - matchers:
        - severity="critical"
      receiver: critical-webhook
    - matchers:
        - severity="warning"
      receiver: default-webhook

receivers:
  - name: default-webhook
    webhook_configs:
      - url: http://localhost:5001/alerts
        send_resolved: true

  - name: critical-webhook
    webhook_configs:
      - url: http://localhost:5001/critical-alerts
        send_resolved: true
